version: "2"

services:
  nodeA:
    image: se-artif-prd.infinera.com/tm3k/trunk-hostenv:29.0
    container_name: nodeA
    privileged: true
    ports:
      - "80"
  nodeZ:
    image: se-artif-prd.infinera.com/tm3k/trunk-hostenv:29.0
    container_name: nodeZ
    privileged: true
    ports:
      - "80"
